### ISSUE TITLE
在没有创建数据库的时候执行rowCountWithWhere 会报错

### ISSUE THREAD

**Issue by donotlazy** [li6185377/LKDBHelper-SQLite-ORM#102]
#LKDBHelper ERROR: -[LKDBHelper executeScalarWithSQL:arguments:]_block_invoke  [Line 323] 
 sql:select count(rowid) from WriteYLKHistory where  UID=? and cate=? 
 args:(
    227,
    2
) 
能不能再执行的时候判断是否存在数据库，不存在的话就创建？

**Comment by li6185377** [comment]
这个只是错误日志，不影响业务逻辑的
