### ISSUE TITLE
不能切换数据库

### ISSUE THREAD

**Issue by Jamie-Ling** [li6185377/LKDBHelper-SQLite-ORM#103]
虽然可以指定dbpath初始化数据库，但是看SDK里面，切换时，扩展还是会调用到 getUsingLKDBHelper，这里面的初始化指定了DB名为 LKDB.db.   貌似不改代码是无法使用切换的数据库了？

**Comment by li6185377** [comment]
不是 ， 每个 Model Class 都重载 getUsingLKDBHelper ， 或者 hook 这个方法吧
