### ISSUE TITLE
升级数据库时新增字段设置的默认值会被覆盖

### ISSUE THREAD

**Issue by icleon** [li6185377/LKDBHelper-SQLite-ORM#106]
项目中使用了这个库，但是这次升级增加了一个字段remainReschduleTimes并且带有默认值3,但是会实际上这个值会被下面的代码处理成默认值是0的情况

![image](https://cloud.githubusercontent.com/assets/16069451/26447334/ad70b654-417a-11e7-8948-f35dc45b1122.png)
使用的是上面这种方式来设置对应字段默认值的

![image](https://cloud.githubusercontent.com/assets/16069451/26447143/b2315b4a-4179-11e7-832d-92606ddbd487.png)

上图所示代码逻辑先alert了表增加了remainReschduleTimes字段这时候该字段已经有一个默认值3了，但是后面又有个逻辑是：alert表成功后会执行一个初始化sql语句，这时候就把改标量设置成了0.

**Comment by li6185377** [comment]
哦  如果有   defaultValue  要用该值去设置，你看下提个 pull request 上来咯
