### ISSUE TITLE
字符串作为主键的时候报 的错误

### ISSUE THREAD

**Issue by hyhSuper** [li6185377/LKDBHelper-SQLite-ORM#112]
sql:select count(rowid) from LocalFileDirTable where  filePath='/Users/allan/Desktop/苹果开发之Cocoa编程Cocoa Programming for Mac OS X/Chapter 02 - Let's Get Started'  
 args:(null) 
 sqlite error :near "s": syntax error

**Comment by li6185377** [comment]
你搜索的 内容里面有 单引号。    这种可以用  NSDictionary 当 where 条件

**Comment by hyhSuper** [comment]
实际上，我就是用的NSDictionary 当where的条件的，后来不用字符串当搜索条件了，回避了这个问题。
