### ISSUE TITLE
FMDatabase里面有个废弃属性

### ISSUE THREAD

**Issue by Cherishforever** [li6185377/LKDBHelper-SQLite-ORM#113]
@property (nonatomic, readonly) BOOL isInTransaction;

- (BOOL)inTransaction __deprecated_msg("Use isInTransaction property instead");

现在报警告，建议处理一下。

**Comment by wenhaoChan** [comment]
现在好像改成 - (BOOL)inTransaction; 这个方法了。希望尽早修改一下

**Comment by li6185377** [comment]
已经修改为  isInTransaction 了
