### ISSUE TITLE
一次性插入10w个文件引起界面卡顿

### ISSUE THREAD

**Issue by hyhSuper** [li6185377/LKDBHelper-SQLite-ORM#114]
使用的是异步函数   + (void)insertArrayByAsyncToDB:(NSArray *)models completed:(void (^ _Nullable)(BOOL))completedBlock
插入数据库，感觉是数据库占用资源比较多造成的

**Comment by li6185377** [comment]
不会的，在异步线程就算是卡死 也不会影响 UI， 是不是有关联的地方？

**Comment by TonyJR** [comment]
这个应该是由FMDB本身限制引起的

**Comment by zuodd** [comment]
上了几万条数据，查询就比较慢了

**Comment by zuodd** [comment]
希望作者可以优化这一块

**Comment by li6185377** [comment]
ORM 本身比较耗性能，一次性插这么多文件，是否考虑下 这个适合在客户端里面做吗？

**Comment by hyhSuper** [comment]
我这边是文件备份，需要把文件信息写入数据库，之前是大批量文件极限测试，目前优化到卡顿1秒左右10w个文件
