### ISSUE TITLE
pod 'FMDB/SQLCipher' pod 'LKDBHelper' 闪退

### ISSUE THREAD

**Issue by 275080225** [li6185377/LKDBHelper-SQLite-ORM#116]
platform :ios,4.3
target 'iOS-Demo' do
    use_frameworks!
    pod 'FMDB/SQLCipher'
    pod 'LKDBHelper'
end

db = [[LKDBHelper alloc]init];
[db setKey:@"123456"];

FMDatabase.m 
下面一行闪退
    int rc = sqlite3_key(_db, [keyData bytes], (int)[keyData length]);

**Comment by li6185377** [comment]
有具体的 log 吗？
