### ISSUE TITLE
最新 swift 4 下，无法获取对象属性，所有对象都是0个属性

### ISSUE THREAD

**Issue by zhanxp** [li6185377/LKDBHelper-SQLite-ORM#117]
最新 swift 4 下，无法获取对象属性，所有对象都是0个属性

**Comment by AegeanCoral** [comment]
https://bugs.swift.org/browse/SR-5748
This can be done by placing @objc on each property (@objc var id: String = "") or by putting @objcMembers on the class itself (@objcMembers class Factory: NSObject) which is like marking everything in the class with @objc (properties and methods).

**Comment by madaoCN** [comment]
> https://bugs.swift.org/browse/SR-5748
> This can be done by placing @objc on each property (@objc var id: String = "") or by putting @objcMembers on the class itself (@objcMembers class Factory: NSObject) which is like marking everything in the class with @objc (properties and methods).

Thanks, you save my life
