### ISSUE TITLE
关于主键的问题

### ISSUE THREAD

**Issue by baozhoua** [li6185377/LKDBHelper-SQLite-ORM#129]
App1.0版本的某个对象实现了
+ (NSString *)getPrimaryKey{
    return @"timeLine";
}
在后续的版本更新中我想设置联合主键，实现
+ (NSArray *)getPrimaryKeyUnionArray
{
    return @[@"name",@"edu"];
}

不知有什么办法可以更改主键吗？目前来说用户覆盖安装的话 ，后续设置联合主键是无效的。

**Comment by li6185377** [comment]
只能自己写 sql 改了
