### ISSUE TITLE
请问如何插入多个模型?

### ISSUE THREAD

**Issue by LuckyChen73p** [li6185377/LKDBHelper-SQLite-ORM#131]
你好, 请问如何插入多个不同的模型?

**Comment by li6185377** [comment]
array 吗？自己写 foreach，内部也有事务批量插入的方法 `+ (void)insertArrayByAsyncToDB:(NSArray *)models;`

**Comment by LuckyChen73p** [comment]
> array 吗？自己写 foreach，内部也有事务批量插入的方法 `+ (void)insertArrayByAsyncToDB:(NSArray *)models;`

谢谢, 我试过了, 可以直接多个模型集成直接调用插入方法就好, 各个模型之间不受影响
