### ISSUE TITLE
更换数据库密码之后，导致写不进数据

### ISSUE THREAD

**Issue by SABeiBei** [li6185377/LKDBHelper-SQLite-ORM#137]
请问更换密码后，数据库打不开，有没有什么类似的回调方法？

方便在回调方法删除数据库，并创建新的。

**Comment by li6185377** [comment]
是直接调用 rekey: 改密码吗？ 这个方法是同步的， 直接删就可以了

**Comment by SABeiBei** [comment]
> 是直接调用 rekey: 改密码吗？ 这个方法是同步的， 直接删就可以了

没有调用rekey：。
我们是2套环境数据库密码不一样，这样，切环境的时候，数据库打不开，没有回调方法去处理这个异常。

我的初衷是希望有这么一个回调方法，在数据库打不开的时候，去处理一些事情。

**Comment by li6185377** [comment]
这个目前你可以 自己 hook 下对应 api，加入自己的逻辑
