### ISSUE TITLE
NSSet可以支持吗？

### ISSUE THREAD

**Issue by dsencheng** [li6185377/LKDBHelper-SQLite-ORM#139]
NSSet可以支持吗？

**Comment by li6185377** [comment]
目前不支持，需要你自己转义下

**Comment by dsencheng** [comment]
我是这样写的，崩溃了。"目前LKDB 还不支持 循环引用。  比如 A 持有 B，   B 持有 A，这种的存储"。
可以帮忙写个示例吗？

`- (id)userGetValueForModel:(LKDBProperty *)property {
    if ([property.sqlColumnName isEqualToString:@"doctorIdSet"]) {
        return self.doctorIdSet.allObjects;
    }
    return nil;
}

- (void)userSetValueForModel:(LKDBProperty *)property value:(id)value {
    if ([property.sqlColumnName isEqualToString:@"doctorIdSet"]) {
        [self.doctorIdSet addObjectsFromArray:value];
    }
}

- (NSMutableSet *)doctorIdSet {
    if (!_doctorIdSet) {
        _doctorIdSet = [NSMutableSet set];
    }
    return _doctorIdSet;
}`
