### ISSUE TITLE
Xcode 11 编译有 warning ，麻烦处理

### ISSUE THREAD

**Issue by XQBoy** [li6185377/LKDBHelper-SQLite-ORM#141]
meta method 'getTableMapping' in category from .../LKDBHelper/libLKDBHelper.a(LKDB+Mapping.o) conflicts with same method from another category
编译提醒此 warning。

**Comment by isdotjim** [comment]
搭个车...
想邀请Repo作者来w3c.group创建项目的对应小组。w3c.group是类似知识星球的社群工具，小组可设置为付费且有赞助功能，同时也是一个区块链主导的创作者社区。这是相关介绍：
http://t.cn/Ai1vLcCU
http://t.cn/Ai1vLcCG
http://t.cn/Ai1vLcCA

**Comment by tanranran** [comment]
+1

**Comment by pengpeng-wang** [comment]
+1，

这个方法有重复，在 NSObject+LKModel.m 和 LKDB+Mapping 中都有getTableMapping，麻烦作者处理下哈

**Comment by li6185377** [comment]
已修复，但是暂时不更新 podspec，等有功能性的再提交。
