### ISSUE TITLE
Swift 数组图片 error 循环引用

### ISSUE THREAD

**Issue by Istroot** [li6185377/LKDBHelper-SQLite-ORM#143]
Error Description: *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: '目前LKDB 还不支持 循环引用。  比如 A 持有 B，   B 持有 A，这种的存储'

使用环境： Xcode 11， Swift

出现场景：模型中的属性有[UIImage]或[Data]这类属性就会报循环引用的错，数据不存在循环引用。

**Comment by li6185377** [comment]
因为你是用了 swift 类型的 Image，Data 吧？ 没有命中对应 基础类型 的判断，会当做自定义Model来处理
