### ISSUE TITLE
在11.0一下系统crash

### ISSUE THREAD

**Issue by renmoqiqi** [li6185377/LKDBHelper-SQLite-ORM#147]
dyld: lazy symbol binding failed: Symbol not found: _sqlite3_key
  Referenced from: /Users/penghe/Library/Developer/CoreSimulator/Devices/3AB5A829-4D00-4498-B3C1-0ABBDB10F5AD/data/Containers/Bundle/Application/4363DF3F-2655-46CD-BDCB-5E3D2201F2D2/SMYCacheKit.app/Frameworks/FMDB.framework/FMDB
  Expected in: /Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 8.1.simruntime/Contents/Resources/RuntimeRoot/usr/lib/libsqlite3.dylib

dyld: Symbol not found: _sqlite3_key
  Referenced from: /Users/penghe/Library/Developer/CoreSimulator/Devices/3AB5A829-4D00-4498-B3C1-0ABBDB10F5AD/data/Containers/Bundle/Application/4363DF3F-2655-46CD-BDCB-5E3D2201F2D2/SMYCacheKit.app/Frameworks/FMDB.framework/FMDB
  Expected in: /Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 8.1.simruntime/Contents/Resources/RuntimeRoot/usr/lib/libsqlite3.dylib

**Comment by li6185377** [comment]
你这边没导入 sqlite 库吧

**Comment by renmoqiqi** [comment]
引用了ios11以下有问题。以上没问题



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 八八九九 <notifications@github.com&gt;
发送时间: 2020年9月9日 15:37
收件人: li6185377/LKDBHelper-SQLite-ORM <LKDBHelper-SQLite-ORM@noreply.github.com&gt;
抄送: renmoqiqi <1297277245@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[li6185377/LKDBHelper-SQLite-ORM] 在11.0一下系统crash (#147)





 
你这边没导入 sqlite 库吧
