### ISSUE TITLE
LKDateFormatter存在严重bug！！！！！！！！！

### ISSUE THREAD

**Issue by WeMadeCode** [li6185377/LKDBHelper-SQLite-ORM#153]
NSString *datestr = @"2019-09-17 15:22:10";

    NSDateFormatter *format = [[NSDateFormatter alloc]init];
    format.generatesCalendarDates = YES; // 造成问题的本质原因 详情见下方链接

    format.dateFormat = @"yyyy-MM-dd HH:mm:ss";

    // data = Tue Sep 17 15:22:10 2019
    NSDate *date = [format dateFromString:datestr];
    NSLog(@"date = %@",date);
    
    // result 为何返回为空？？？？你把generatesCalendarDates改成false试试
    NSString *result = [NSString stringWithFormat:@"%@",date];
    NSLog(@"result = %@",result);

问题本质原因：https://developer.apple.com/documentation/foundation/nsdateformatter/1411107-generatescalendardates?language=objc

**Comment by li6185377** [comment]
```
/// 需要外部实现对应 API
@interface LKDBUtils (output)

// LKDateFormatter 创建完毕， 可以修改对应属性
+ (void)onCreateWithDateFormatter:(NSDateFormatter *)dateFormatter;

// NSNumberFormatter 创建完毕， 可以修改对应属性
+ (void)onCreateWithNumberFormatter:(NSNumberFormatter *)numberFormatter;

@end
```

已提供对应创建回调，可自行修改
