### ISSUE TITLE
调用：deleteWithWhere删除数据后，在手机设置->iphone储存空间：找到APP看文稿数据会有删除不干净的垃圾数据。

### ISSUE THREAD

**Issue by Jdb156158** [li6185377/LKDBHelper-SQLite-ORM#159]
会产生垃圾数据：
![image](https://user-images.githubusercontent.com/18107143/153581970-f9542da2-9bc7-4b73-84fe-6b5c856de11a.png)

写data+时间戳的数据怎么删除哇？
每在表中插入一条数据，就会有一个data，但是调用deleteWithWhere删除了表中这个数据后，这个data还在

**Comment by li6185377** [comment]
/**
 *	@brief	Clear Unused Data File
            if you property has UIImage or NSData, will save their data in the (documents dir)
 *
 *	@param 	modelClass      entity class
 *	@param 	columns         UIImage or NSData Column Name
 */
+ (void)clearNoneImage:(Class)modelClass columns:(NSArray<NSString *> *)columns;
+ (void)clearNoneData:(Class)modelClass columns:(NSArray<NSString *> *)columns;
