### ISSUE TITLE
性能如何，试着插入 5000 条数据，耗时大概 2.4s

### ISSUE THREAD

**Issue by loveway** [li6185377/LKDBHelper-SQLite-ORM#162]

**Comment by li6185377** [comment]
性能不算太强，内部是采用 KVC 来获取和设置属性值。性能对比 可以参考 YYModel Performance，JSONModel 和 MJExtension 都是用 KVC。

**Comment by loveway** [comment]
您的邮件已收到，谢谢。                                  -----Loveway丶

**Comment by li6185377** [comment]
数据量大就放异步 + Loading ，该库主要解决手写 SQL 的问题。

**Comment by loveway** [comment]
您的邮件已收到，谢谢。                                  -----Loveway丶
