### ISSUE TITLE
存储 UIImage 数组问题

### ISSUE THREAD

**Issue by LAnqxpp** [li6185377/LKDBHelper-SQLite-ORM#167]
从相册获取图片  类型  UIImage  *image 存到数据库没有问题，self.image = image 没有问题
打印储存直接存 <UIImage:0x283290750 anonymous {1702, 1276} renderingMode=automatic>

但是 @[UIIImage] 放到数组存储  获取 赋值 self.image = @[UIIImage][0]   不展示
<__NSArrayM 0x280e102d0>(
<UIImage:0x283290c60 named(?) {0, 0} renderingMode=automatic>,
<UIImage:0x283291320 named(?) {0, 0} renderingMode=automatic>
)

**Comment by li6185377** [comment]
不支持 UIImage 作为二级对象存储（比如 放到 NSArray、NSDictionary 中）
