### ISSUE TITLE
'searchWithSQL' is returning a nil objects and must add 'FROM table'

### ISSUE THREAD

**Issue by alaaghribi** [li6185377/LKDBHelper-SQLite-ORM#17]
Hi,
I just tried the new 'searchWithSQL' method, and it looks like it's returning the correct number of objects, BUT with nil fields. Plus, I need to add 'FROM table', otherwise, it'll indicate that there is no column named 'category' in my case.

NSMutableArray\* arrayOfCategories=[globalHelper searchWithSQL:@"SELECT DISTINCT category FROM Transactions" toClass:[Transaction class]];

//Here it's returning 2 Transaction objects, with nil fields.
//the FROM Transactions is mandatory, or it'll not find category column.

Can you please check that?

Thank you very much.

**Comment by halocq** [comment]
[[BCContact getUsingLKDBHelper] searchWithSQL:@"select distinct group_name from @t order by group_name desc" toClass:[self class]] 这样获取来的是重复的BCContact，而不是不重复group_name
