### ISSUE TITLE
Crash in the dbHelperWithPath method

### ISSUE THREAD

**Issue by alaaghribi** [li6185377/LKDBHelper-SQLite-ORM#37]
Hi,
I usually have (not always) a crash in the dbHelperWithPath method, without any information:
![screen shot 2015-01-09 at 3 02 08 pm](https://cloud.githubusercontent.com/assets/2395568/5680670/c3131f62-9810-11e4-9339-34554807ca14.png)
Do you have an idea of the source of the problem and can you please fix it, I tried something but did not achieve it .
Thank you.

**Comment by li6185377** [comment]
possible: many threads at the same time  foreach array, add a synchronization lock

**Comment by alaaghribi** [comment]
What do you mean by a synchronization lock ? I though that LKDB already creates a queue so that we don't have many table access at the same time, no ?

**Comment by li6185377** [comment]
when foearch dbArray add lock
![qq20150111-1 2x](https://cloud.githubusercontent.com/assets/1924211/5694943/2c99b2e0-99bd-11e4-812f-785c2446dabd.png)

**Comment by alaaghribi** [comment]
I just forgot to say: THANK YOU VERY MUCH !
