### ISSUE TITLE
Model produce physical copy of image repetadly 

### ISSUE THREAD

**Issue by Dev-iOS** [li6185377/LKDBHelper-SQLite-ORM#38]
i am having model in which one property is "UIImage" type and in database that column is "Text" type. 

This library have one feature, which create physical image locally and store that image name in database, vice versa.

But i am facing one issue, even i update model that time library create new physical copy of image for the same record but old copy of image won't deleted. So My app size increasing due to keeps unwanted image files.  

Any way to hook some where else so it can be help me.

**Comment by li6185377** [comment]
![image](https://cloud.githubusercontent.com/assets/1924211/6362721/4076ddde-bccb-11e4-9b87-9fc2b5f071f7.png)
![image](https://cloud.githubusercontent.com/assets/1924211/6362758/8b1d3856-bccb-11e4-88d1-feb80d206d61.png)
LKDBhelper has a function

**Comment by Dev-iOS** [comment]
Hi, thanks for your answer.
