### ISSUE TITLE
方法不执行

### ISSUE THREAD

**Issue by FutureChen** [li6185377/LKDBHelper-SQLite-ORM#40]
-(id)userGetValueForModel:(LKDBProperty*)property;
-(void)userSetValueForModel:(LKDBProperty*)property value:(id)value;
这两个方法都不执行

我的模型中嵌套着模型，所以建立了两个表，我想要在这两个方法中，将对应字段改成存被嵌套模型的主键。发现不执行。

并且发现，数据库中，LKDBHelper 貌似已经自动处理了模型中嵌套模型？会自动生成两个表？
{"DB_PKeyValue":{"rowId":"0"},"DB_Type":"DB_Type_Model","DB_Class":"zijinSocketReallContent","DB_RowId":1,"DB_TableName":"zijinSocketReallContent"}还是sqlite的功能呢？

并且表示您提供的DEMO 中也不执行

**Comment by li6185377** [comment]
要执行 这两个方法 需要在你的类里 调用 
![image](https://cloud.githubusercontent.com/assets/1924211/7980153/bb4a202a-0ad7-11e5-9df5-1531dd6d13ac.png)
我demo 里面注释掉了 你可以看下

**Comment by FutureChen** [comment]
那  模型嵌套模型会自动 生成两个表也是 LKDBHelper的功劳嘛？

**Comment by li6185377** [comment]
en

**Comment by FutureChen** [comment]
好吧 ，牛逼，谢谢解答
