### ISSUE TITLE
浮点型的 double或者float 的问题

### ISSUE THREAD

**Issue by majun8934** [li6185377/LKDBHelper-SQLite-ORM#41]
也遇到这种存浮点型后，取出的东西不对的问题。。
我的一个model里有个price字段是double型的,在查询中，where 用的是 @“price” < 50000 这样的。
取出的数据的price 基本不对..     如果price改成int型后，是没问题的..

发现是在建表的地方有：
        if ([columnType isEqualToString:LKSQL_Type_Double]) {
            columnType = LKSQL_Type_Text;
        }
这种应该是double的小于，大于的条件查询，变成了text的小于大于查询了？

如果是为了适配精度问题，却会导致这种查询的错误，得不偿失啊。。

**Comment by majun8934** [comment]
发现小数点double可以精确到6位，也基本能满足大多应用的需求吧

**Comment by li6185377** [comment]
where 可以改下用的是 @“(0+price) < 50000”,  强转为数值    这样子对比就没错了

**Comment by li6185377** [comment]
double 6位是大部分满足了。  还是有些场景需要高精度的，所以还是保证   存的数据为主。  对比可以按上面那条回复来做
