### ISSUE TITLE
请教一个使用场景

### ISSUE THREAD

**Issue by mrkey0310** [li6185377/LKDBHelper-SQLite-ORM#42]
例如浏览记录这个模型其实是跟原来某个数据的模型是一样的，但是它们是两个不同的数据源，那么请问如何为同一种数据模型建两个表呢？还是说继承一个子类更为安全？

**Comment by li6185377** [comment]
可以继承一个子类。 或者多一个属性来记录来源

**Comment by mrkey0310** [comment]
好吧...那还是内部创建一个子类比较安全....感谢解答

**Comment by mrkey0310** [comment]
已经使用到项目当中，效果很理想，但是有个情况就是我建立了一个BaseModel 实现基本方法, 然后PostModel继承于BaseModel， 因为需要同一属性需要建两个表的原因，我创建一个HistoryModel继承于PostModel， 奇怪的是，PostModel的操作都是正常的，但是HistoryModel 在建表都不能

**Comment by li6185377** [comment]
你有重载那两个类的  getTableName 方法吗？
