### ISSUE TITLE
Swift 可以用这个吗

### ISSUE THREAD

**Issue by zhangao0086** [li6185377/LKDBHelper-SQLite-ORM#48]
如题

**Comment by li6185377** [comment]
没有原生的swift版。 不过 swift 本来就可以调用OC   不过应该没办法对swift的model 进行存储

**Comment by zhangao0086** [comment]
Hi @li6185377 
如果 Model 的属性有了变化，如添加了新的属性，目前是不能动态更新表结构的吧

**Comment by li6185377** [comment]
支持动态属性的。  但是只能动态增加列 ， 不能修改

**Comment by zhangao0086** [comment]
:+1:
