### ISSUE TITLE
Use of undeclared identifier 'SQLITE_OPEN_READWRITE'

### ISSUE THREAD

**Issue by SmallBlackCat** [li6185377/LKDBHelper-SQLite-ORM#56]
![image](https://cloud.githubusercontent.com/assets/5243343/12077171/38ab0bda-b210-11e5-8fe6-240cd92852a8.png)
额，你好我更新了下pod,出现了编译错误，`Use of undeclared identifier 'SQLITE_OPEN_READWRITE `

```
platform :ios, '7.0'
pod 'FMDB/SQLCipher',:head
pod 'LKDBHelper',:head
```
我看了下 `splite3.h`里面有定义，但是没有看到`LKDBhelper`哪里引用了 `sqlite3.h`文件
是不是我哪里设置不对呢,我新建了一个项目，也是出现了这个错误。

**Comment by SmallBlackCat** [comment]
我在 `LKDBHelper.h` 头文件里面导入了 `#import "sqlite3.h"`就可以编译通过了

**Comment by li6185377** [comment]
嗯。 已修改

**Comment by SmallBlackCat** [comment]
谢啦
