### ISSUE TITLE
模型里面有一个数组，数组里是另外一个模型如何处理？

### ISSUE THREAD

**Issue by malaimoo** [li6185377/LKDBHelper-SQLite-ORM#57]
2016-01-04 11:52:44.061 MNCats[8575:864551] <INFO> Bugly: BlockMonitor: monitor is stop.
2016-01-04 11:52:44.061 MNCats[8575:864551] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[WorkSysTimeModel countByEnumeratingWithState:objects:count:]: unrecognized selector sent to instance 0x7fb50593abe0'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010f94ce65 __exceptionPreprocess + 165
	1   libobjc.A.dylib                     0x0000000110ad5deb objc_exception_throw + 48
	2   CoreFoundation                      0x000000010f95548d -[NSObject(NSObject) doesNotRecognizeSelector:] + 205
	3   CoreFoundation                      0x000000010f8a290a ___forwarding___ + 970
	4   CoreFoundation                      0x000000010f8a24b8 _CF_forwarding_prep_0 + 120
	5   Foundation                          0x000000010f30c1f4 -[NSObject(NSKeyValueCoding) setValuesForKeysWithDictionary:] + 139
	6   MNCats                              0x000000010c3d746d -[BaseModel initWithDic:] + 141
	7   MNCats                              0x000000010c2fd387 -[WorkSysModel setValue:forKey:] + 487
	8   MNCats                              0x000000010c4a6d38 -[NSObject(LKModel) modelSetValue:value:] + 3368
	9   MNCats                              0x000000010c49ba7b -[LKDBHelper(DatabaseExecute) executeResult:Class:tableName:] + 1067
	10  MNCats                              0x000000010c49abac __56-[LKDBHelper(DatabaseExecute) searchWithRAWSQL:toClass:]_block_invoke + 140
	11  MNCats                              0x000000010c492db7 -[LKDBHelper executeDB:] + 199
	12  MNCats                              0x000000010c49aa4e -[LKDBHelper(DatabaseExecute) searchWithRAWSQL:toClass:] + 318
	13  MNCats                              0x000000010c49a8d5 -[LKDBHelper(DatabaseExecute) searchWithSQL:toClass:] + 133
	14  MNCats                              0x000000010c4a8ab7 -[NSObject(LKModel) db_objectWithDictionary:] + 1799
	15  MNCats                              0x000000010c4a8112 -[NSObject(LKModel) db_modelWithJsonValue:] + 370
	16  MNCats                              0x000000010c4a6c71 -[NSObject(LKModel) modelSetValue:value:] + 3169
	17  MNCats                              0x000000010c49ba7b -[LKDBHelper(DatabaseExecute) executeResult:Class:tableName:] + 1067
	18  MNCats                              0x000000010c499af3 __52-[LKDBHelper(DatabaseExecute) searchBaseWithParams:]_block_invoke + 387
	19  MNCats                              0x000000010c4931ac __24-[LKDBHelper executeDB:]_block_invoke171 + 108
	20  MNCats                              0x000000010c43232c __30-[FMDatabaseQueue inDatabase:]_block_invoke + 124
	21  libdispatch.dylib                   0x00000001114b749b _dispatch_client_callout + 8
	22  libdispatch.dylib                   0x000000011149bfb5 _dispatch_barrier_sync_f_invoke + 393
	23  MNCats                              0x000000010c43225d -[FMDatabaseQueue inDatabase:] + 301
	24  MNCats                              0x000000010c492f90 -[LKDBHelper executeDB:] + 672
	25  MNCats                              0x000000010c499806 -[LKDBHelper(DatabaseExecute) searchBaseWithParams:] + 2838
	26  MNCats                              0x000000010c49a34d -[LKDBHelper(DatabaseExecute) searchBase:columns:where:orderBy:offset:count:] + 685
	27  MNCats                              0x000000010c4983e5 -[LKDBHelper(DatabaseExecute) search:where:orderBy:offset:count:] + 181
	28  MNCats                              0x000000010c4a34ee +[NSObject(LKDBHelper) searchWithWhere:orderBy:offset:count:] + 190
	29  MNCats                              0x000000010c2e6875 -[BMStaffVC getDBEmployee] + 69
	30  MNCats                              0x000000010c2e68d7 -[BMStaffVC getAllEmployee] + 55
	31  MNCats                              0x000000010c2e61e2 -[BMStaffVC viewDidLoad] + 354
	32  UIKit                               0x000000010d645f98 -[UIViewController loadViewIfRequired] + 1198
	33  UIKit                               0x000000010d64bf4f -[UIViewController __viewWillAppear:] + 120
	34  UIKit                               0x000000010d67be44 -[UINavigationController _startCustomTransition:] + 1203
	35  UIKit                               0x000000010d68c23f -[UINavigationController _startDeferredTransitionIfNeeded:] + 712
	36  UIKit                               0x000000010d68d3af -[UINavigationController __viewWillLayoutSubviews] + 57
	37  UIKit                               0x000000010d833ff7 -[UILayoutContainerView layoutSubviews] + 248
	38  UIKit                               0x000000010d5664a3 -[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 703
	39  QuartzCore                          0x000000010d22d59a -[CALayer layoutSublayers] + 146
	40  QuartzCore                          0x000000010d221e70 _ZN2CA5Layer16layout_if_neededEPNS_11TransactionE + 366
	41  QuartzCore                          0x000000010d221cee _ZN2CA5Layer28layout_and_display_if_neededEPNS_11TransactionE + 24
	42  QuartzCore                          0x000000010d216475 _ZN2CA7Context18commit_transactionEPNS_11TransactionE + 277
	43  QuartzCore                          0x000000010d243c0a _ZN2CA11Transaction6commitEv + 486
	44  UIKit                               0x000000010d4a9f7c _UIApplicationHandleEventQueue + 7329
	45  CoreFoundation                      0x000000010f878a31 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	46  CoreFoundation                      0x000000010f86e95c __CFRunLoopDoSources0 + 556
	47  CoreFoundation                      0x000000010f86de13 __CFRunLoopRun + 867
	48  CoreFoundation                      0x000000010f86d828 CFRunLoopRunSpecific + 488
	49  GraphicsServices                    0x00000001122acad2 GSEventRunModal + 161
	50  UIKit                               0x000000010d4af610 UIApplicationMain + 171
	51  MNCats                              0x000000010c3d71bf main + 111
	52  libdyld.dylib                       0x00000001114ec92d start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException

不知道是不是这个原因导致的崩溃？

**Comment by li6185377** [comment]
可能你模型里面 重写了set 方法？

**Comment by shenguanjiejie** [comment]
我也是model1中有数组(model2),我的问题是这个数组(model2)无法写入数据库(也可能是写入了无法search到,search到model1后发现数组(model2)是nil).不过我没有崩溃,也没有报任何错,model1和model2中都有属性重写了getter方法,不过我并没有对这些属性LKSQL_Mapping_Inherit,请问问题出在哪里?谢谢!

**Comment by shenguanjiejie** [comment]
我的问题已经解决,不是作者的问题,是我这边的bug.可以忽略该问题

**Comment by malaimoo** [comment]
我的也没问题了，重启了一下xcode 就可以了。close掉吧，谢谢！
