### ISSUE TITLE
getUsingLKDBHelper 方法的逻辑问题

### ISSUE THREAD

**Issue by xyj6989** [li6185377/LKDBHelper-SQLite-ORM#60]
在 `NSObject (LKDBHelper_Execute)`这个类别里的数据操作方法中最终调用的的是`[LKDBHelper getUsingLKDBHelper]` 这个方法，这个方法默认返回一个固定路径的数据库，现在遇到的问题是，我在多数据库存储中，进行关联存储，被关联的对象会被存储到`[LKDBHelper getUsingLKDBHelper]`这个默认生成的数据库中，而不是我自定义路径的数据库。

**Comment by li6185377** [comment]
在你关联的 model 中 也要重载  getUsingLKDBHlper  返回你要存储的 db

**Comment by xyj6989** [comment]
每个关联的model都要重写 getUsingLKDBHlper ,或者我再加一层中间的baseModel。如果多个数据库不同的model来操作，会产生很多中间层的model，是否可以在操作的时候捕获下当前的上下文来取到当前操作的数据库。

**Comment by li6185377** [comment]
这个不太好。很可能同一个model 被存放在了不同的数据库。
