### ISSUE TITLE
 sqlite error :database is locked 

### ISSUE THREAD

**Issue by i5ting** [li6185377/LKDBHelper-SQLite-ORM#61]
#LKDBHelper ERROR: __35-[LKDBHelper executeSQL:arguments:]_block_invoke  [Line 271] 
 sql:update PRInventoryAll set product_id=?,all_count=?,product_name=?,product_logo=?,user_id=? where  rowid=79 
 args:(
    56d7e3b74540cd3b39a4c0fd,
    211,
    "\U4e00\U4e2a",
    "",
    56d692521c80d09b2adac991
) 
 sqlite error :database is locked

**Comment by i5ting** [comment]
WARNING: Requested sleep of 84 milliseconds, but SQLite returned 1000. Maybe SQLite wasn't built with HAVE_USLEEP=1?

**Comment by li6185377** [comment]
数据库是不是在电脑那边已经打开了

**Comment by i5ting** [comment]
确实是的，可是我用sql更新就没有任何问题

**Comment by i5ting** [comment]
提示一下呗，当出现锁的时候，估计很多人都反应不过来，哈哈
