### ISSUE TITLE
入库时，如何护理某一个属性

### ISSUE THREAD

**Issue by shnuzxw** [li6185377/LKDBHelper-SQLite-ORM#65]
当我需要将一个模型入库时，有些属性要求不能入库，我应该如何处理呢？

**Comment by li6185377** [comment]
可以设置这个属性由自己维护。 设置 `+ (void)setUserCalculateForCN:(NSString*)columnName;` 并重载 
![image](https://cloud.githubusercontent.com/assets/1924211/15248806/bd9d0c58-194e-11e6-8a14-eb313faa7498.png)

**Comment by shnuzxw** [comment]
我可以忽略这个属性吗？创建数据库的时候就不考虑该属性，是不是增加一个忽略的方法比较好呢？就像JsonModel可以设置忽略的字段一样！

**Comment by li6185377** [comment]
有支持的 + (void)removePropertyWithColumnName:(NSString*)columnName;

**Comment by shnuzxw** [comment]
这个方法怎么用，我在什么时候调用

**Comment by shnuzxw** [comment]
已解决，非常感谢哦！
