### ISSUE TITLE
LKDBHelper-SQLite-ORM release模型下不能正常运行吗？

### ISSUE THREAD

**Issue by QinKingHan** [li6185377/LKDBHelper-SQLite-ORM#66]
LKDBHelper-SQLite-ORM release模型下获取数据错乱。但在debug模式下好好的。这是什么情况？

**Comment by li6185377** [comment]
没影响的。是不是有基础类型外的系统对象?

**Comment by QinKingHan** [comment]
感谢你的回复，基础类型外的系统对象 这句话怎么理解？ 谢谢

**Comment by QinKingHan** [comment]
我没呀 用cocosPod, 直接拉应该没影响吧

**Comment by shnuzxw** [comment]
他说的基础数据以为的对象，就是指除了NSString、NSInteger等基础数据类型之外的数据，如NSData等

**Comment by QinKingHan** [comment]
嗯，谢谢大家了

**Comment by QinKingHan** [comment]
+ (NSMutableArray*)searchWithWhere:(id)where orderBy:(NSString*)orderBy offset:(NSInteger)offset count:(NSInteger)count; 可以根据对应表查询吗

**Comment by li6185377** [comment]
Class 对应的表， 如果需要自己指定表名  使用  `/**
 *	@brief	query table
 *  
 *  @param 	params query condition
 */
- (NSMutableArray*)searchWithParams:(LKDBQueryParams*)params;`
