### ISSUE TITLE
use_frameworks!时编译出错

### ISSUE THREAD

**Issue by songhailiang** [li6185377/LKDBHelper-SQLite-ORM#67]
podfile里添加了use_frameworks!时编译出错，错误信息如下：
LKDBHelper.h:9:9: Include of non-modular header inside framework module 'LKDBHelper.LKDBHelper'
是引入FMDB的代码报的错，请问该如何解决？非常感谢！

**Comment by li6185377** [comment]
恩。FMDB 头文件要用全路径去import，已经修复了。 重新 pod update 下
