### ISSUE TITLE
求助：如果数据库里面有个字段存储的是一个数组（数组中是一个对象）如何查询这个对象

### ISSUE THREAD

**Issue by deanli08** [li6185377/LKDBHelper-SQLite-ORM#71]
您好，我现在遇到个问题，就是 
    LKTest* test = [[LKTest alloc]init];
    test.name = @"zhan san";
    test.age = 16;
    
    //外键  foreign key
    LKTestForeign* foreign = [[LKTestForeign alloc]init];
    foreign.address = @":asdasdasdsadasdsdas";
    foreign.postcode  = 123341;
    foreign.addid = 213214;
    test.address = foreign;
那我应该如何去查询LKTestForeign里面postcode为123341的值，返回LKTest

**Comment by li6185377** [comment]
默认关联的目前还没有办法。 建议你用 UserCalculate， 自己维护这种关系。

**Comment by deanli08** [comment]
好的 了解了。谢谢了
