### ISSUE TITLE
NSObject+LKModel.m 428行有个判断是不是写错了？

### ISSUE THREAD

**Issue by iwill** [li6185377/LKDBHelper-SQLite-ORM#72]
[NSObject+LKModel.m 428行](https://github.com/li6185377/LKDBHelper-SQLite-ORM/blob/master/LKDBHelper/Helper/NSObject%2BLKModel.m#L428) 有个判断是不是写错了？

```objc
if (model.db_inserting == NO && [clazz getModelInfos] > 0) ....
```

`[clazz getModelInfos]` 方法返回值类型是 `LKModelInfos *`，这里拿来和 `0` 比较大小。

**Comment by li6185377** [comment]
cool~  已改， thanks
