### ISSUE TITLE
子类获取不到父类属性，能解决下这个吗

### ISSUE THREAD

**Issue by BrownCN023** [li6185377/LKDBHelper-SQLite-ORM#76]
class UserModel
@property String u_id;
@property String u_name;

class UserExpandModel extends UserModel

[uem saveToDB](可能还有其他方法)
Error:UserExpandModel 没有属性

class_copyPropertyList([self class],&pcount) //pcount 取出个数为0
这个能解决下吗?

**Comment by li6185377** [comment]
/**
 *	@brief Containing the super class attributes	设置是否包含 父类 的属性
 */
+ (BOOL)isContainParent;
重载返回YES

**Comment by BrownCN023** [comment]
@li6185377  明白了～ 没注意看...
