### ISSUE TITLE
初次使用,有几个小问题.麻烦您帮忙看看

### ISSUE THREAD

**Issue by zhoupIT** [li6185377/LKDBHelper-SQLite-ORM#79]
1.生成的数据库表的列表是乱序的,怎么才能排序?方便看数据,因为我们一张表的数据太多
2.数据库的表可以统一的提前创建吗

**Comment by li6185377** [comment]
1. 目前内部使用了 NSDictionary 进行 property 跟 column 的映射， 所以列是乱序的，除非内部再用个 array 去保存获取的顺序
2. 这个可以不用关系，当你插入数据的时候，底层会自动帮你创建

**Comment by Ronda90** [comment]
当model属性有增减的时候，对应的数据库表会自动增减字段么？

**Comment by li6185377** [comment]
会的，全自动

**Comment by zhoupIT** [comment]
第二个问题,我一般会先查询数据是否存在,查询的时候是不会创建的吧,还有事务插入的时候.

**Comment by li6185377** [comment]
有私有函数，你可以自己声明出来调用
