### ISSUE TITLE
能更新一下 init方法里面的沙河路径吗 重载的话 DB 也是在Docment 下面 也会被拒绝

### ISSUE THREAD

**Issue by yuyangdexue** [li6185377/LKDBHelper-SQLite-ORM#80]
能更新一下 init方法里面的沙河路径吗 重载的话 DB 也是在Docment 下面 也会被拒绝

**Comment by li6185377** [comment]
可以用 Method Swizzle 替换掉 具体方法的实现

**Comment by songhailiang** [comment]
@yuyangdexue 这个库会影响到AppStore上架？我之前用的这个没有被拒绝，苹果审核规则调整了？

**Comment by WildDylan** [comment]
这个库不会影响到上架，我们已经审核通过了很多版本。
