### ISSUE TITLE
你好，我更新到2.4了，在xcode8.0上，读取数据库中的nssmutablearray还是为nil呢，怎么解决

### ISSUE THREAD

**Issue by lijiee** [li6185377/LKDBHelper-SQLite-ORM#84]
![Uploading 0908A04F-2C60-427C-8CB8-8E938171C5FF.png…]()
在iOS 9以下都是正常 的

**Comment by li6185377** [comment]
你可以用 Demo-iOS 试下， 或者 你可以把你的代码抽下  发给我看下
