### ISSUE TITLE
有些方法没必要暴露出去

### ISSUE THREAD

**Issue by yoimhere** [li6185377/LKDBHelper-SQLite-ORM#86]
比如 LKDBHelper 类中的  setDBName  setDBPath 中的这2个方法,暴露出去会给使用者带来错误的使用方法，如果使用者手动调用setDBName or setDBPath加上LKDBHelper缓存某些情况下会导致db路径错误

**Comment by li6185377** [comment]
大部分使用DBName 就好，但是有时候数据库是已经存在的 就需要制定路径了
