### ISSUE TITLE
swfit 3.0中有问题

### ISSUE THREAD

**Issue by yzcoder** [li6185377/LKDBHelper-SQLite-ORM#90]
在swift3.0下  int类型和float类型存不进去，而且查询的时候如果字段是SwiftString类型，是查询不到结果的。
不知道是不是我的操作有问题，你可以看看你的demo，里面postcode等属性也是存不进表的

**Comment by li6185377** [comment]
我试了下 Demo 没有问题。 float int 都是存取成功的
