### ISSUE TITLE
使用加密功能导致崩溃

### ISSUE THREAD

**Issue by spWang** [li6185377/LKDBHelper-SQLite-ORM#92]
按照说明, 使用了cocoaPods,
pod 'FMDB/SQLCipher'
pod 'LKDBHelper'
顺序就是这样, 并没有指定版本号

我新建一个数据库(之前并不存在),然后设置加密的key,然后崩溃,设置加密的key代码如下, 在初始化helper后去设置的,重载了getUsingLKDBHelper方法
+(LKDBHelper *)getUsingLKDBHelper
{
    static LKDBHelper* _helper;
    static dispatch_once_t onceToken;
    dispatch_once(&onceToken, ^{
        NSString *path = @"/Users/mac-pro/Desktop/data1.db";
        _helper = [[LKDBHelper alloc]initWithDBPath:path];
    });
    
    NSString *encryptKey = @"aaabbbccc"
    BOOL result = [_helper setKey:encryptKey];
        if (!result) {
            NSLog(@"数据库加密失败!");
        }else {
            NSLog(@"数据库加密成功");
        }
    return _helper;
}

请问是使用方式上有什么问题吗?
崩溃在sqlite.c里,提示pCache为NULL
/* 
** Return the total number of referenced pages held by the cache.
*/
SQLITE_PRIVATE int sqlite3PcacheRefCount(PCache *pCache){
  return pCache->nRef;
}

**Comment by li6185377** [comment]
加密这块都是靠 FMDB/SQLCipher, 是不是路径问题，你可以用 initWithDBName 来初始化

**Comment by hilen** [comment]
Demo 工程加密后用，代码返回加密成功。但是用  `DB Browser for SQLite` 这个 App 依然能看到里面的数据，不需要输入密码？

**Comment by li6185377** [comment]
SQLCipher 需要创建数据库后，立马加密，不能对现有的数据库加密，数据库已有数据后 也不可加密

**Comment by hilen** [comment]
嗯，我是把本地的数据库删除后再 run 的，好像不行
```
//重载选择 使用的LKDBHelper
+(LKDBHelper *)getUsingLKDBHelper
{
    static LKDBHelper* db;
    static dispatch_once_t onceToken;
    dispatch_once(&onceToken, ^{
        NSString* dbpath = [NSHomeDirectory() stringByAppendingPathComponent:@"asd/asd.db"];
        db = [[LKDBHelper alloc]initWithDBPath:dbpath];
        [db setkey(@"123456")]
    });
    return db;
}
```
