### ISSUE TITLE
基于LKDBHelper 开发的库 pod lib 验证产生警告, 麻烦作者修改下

### ISSUE THREAD

**Issue by bosong** [li6185377/LKDBHelper-SQLite-ORM#94]
LKDBHelper ( 2.4.1)
   - WARN  |  xcodebuild:  LKDBHelper/LKDBHelper/Helper/NSObject+LKDBHelper.m:174:11: warning: null passed to a callee that requires a non-null argument [-Wnonnull]
    - WARN  | xcodebuild:  LKDBHelper/LKDBHelper/Helper/NSObject+LKDBHelper.m:180:19: warning: null passed to a callee that requires a non-null argument [-Wnonnull]
    - WARN  | xcodebuild:  LKDBHelper/LKDBHelper/Helper/NSObject+LKDBHelper.m:187:11: warning: null passed to a callee that requires a non-null argument [-Wnonnull]

**Comment by li6185377** [comment]
已修复
