### ISSUE TITLE
在事务状态下 没法创建表， 怎么处理呀

### ISSUE THREAD

**Issue by QinKingHan** [li6185377/LKDBHelper-SQLite-ORM#95]
[https://github.com/li6185377/LKDBHelper-SQLite-ORM/issues/73](url)
我根据这个问题 事务插入之前 现创建表 还是不行呀

**Comment by li6185377** [comment]
可以在事务前创建表下, 比如先search 下

**Comment by QinKingHan** [comment]
嗯呢 可以了，🙏
