### ISSUE TITLE
如果保存一个数组，数组 里面都是自定义的model 对象

### ISSUE THREAD

**Issue by emodeqidao** [li6185377/LKDBHelper-SQLite-ORM#97]
如果插入一个数组？？

**Comment by heyehao2008** [comment]
这种情况会自动为数组里面的Model建张表。当然最好在model里面设置好主键、需要过滤的字段等信息

**Comment by emodeqidao** [comment]
还有一个问题，我给数据库加了 SQLCipher ，为什么 一定要 pod 'FMDB/SQLCipher'  这样写 才可以？ 分开写就不行？？

**Comment by li6185377** [comment]
因为基于了 FMDB， FMDB内部判断是否支持加密 是基于  FMDB/SQLCipher 相关宏设置的
