### ISSUE TITLE
NSData 类型的存储问题

### ISSUE THREAD

**Issue by qianlishun** [li6185377/LKDBHelper-SQLite-ORM#98]
NSData 没有处理成blob类型存储到数据库，是 以text类型存的一个指向data缓存文件的文件名。
使用 deleteToDB 删除包含 NSData 的数据，并不会将对应的缓存文件也删除。
如果我要做处理的话，请问在哪里改呢？
谢谢！

**Comment by li6185377** [comment]
`+ (void)clearNoneData:(Class)modelClass columns:(NSArray<NSString *> *)columns;` LKDBHelper.h 有这个 清空无效文件的方法

**Comment by qianlishun** [comment]
谢谢！我懒省事直接把nsdata存数据库里面了。。。后面看情况再选择方法。感谢解答。

**Comment by zuodd** [comment]
如果我想清空指定的NSData怎么操作？clearNoneData 这个是全部清理掉吧？
